package com.segmed;
// default package
// Generated 16/05/2018 21:50:25 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientecolaborador generated by hbm2java
 */
@Entity
@Table(name = "CLIENTECOLABORADOR", schema = "SEGMED")
public class BDClientecolaborador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoColaborador;
	private BDClientes clientes;
	private String nome;
	private String cpf;
	private String rg;
	private Date nascimento;
	private String funcao;
	private String telefone;
	private Set<BDExame> exames = new HashSet<BDExame>(0);

	public BDClientecolaborador() {
	}

	public BDClientecolaborador(int codigoColaborador) {
		this.codigoColaborador = codigoColaborador;
	}

	public BDClientecolaborador(BDClientes clientes, String nome, String cpf, String rg,
			Date nascimento, String funcao, String telefone) {
		this.clientes = clientes;
		this.nome = nome;
		this.cpf = cpf;
		this.rg = rg;
		this.nascimento = nascimento;
		this.funcao = funcao;
		this.telefone = telefone;
	}

	@Id
	@GeneratedValue(generator="seq_colaborador", strategy=GenerationType.AUTO)
	@SequenceGenerator(name="seq_colaborador", sequenceName="seq_colaborador", initialValue=1)
	@Column(name = "codigo_colaborador", unique = true, nullable = false)
	public int getCodigoColaborador() {
		return this.codigoColaborador;
	}

	public void setCodigoColaborador(int codigoColaborador) {
		this.codigoColaborador = codigoColaborador;
	}

	@ManyToOne
	@JoinColumn(name = "codigo_cliente", referencedColumnName = "codigo_cliente")
	public BDClientes getClientes() {
		return this.clientes;
	}

	public void setClientes(BDClientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "nome", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cpf", length = 30)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "rg", length = 30)
	public String getRg() {
		return this.rg;
	}

	public void setRg(String rg) {
		this.rg = rg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nascimento", length = 13)
	public Date getNascimento() {
		return this.nascimento;
	}

	public void setNascimento(Date nascimento) {
		this.nascimento = nascimento;
	}

	@Column(name = "funcao", length = 30)
	public String getFuncao() {
		return this.funcao;
	}

	public void setFuncao(String funcao) {
		this.funcao = funcao;
	}

	@Column(name = "telefone", length = 30)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientecolaborador")
	public Set<BDExame> getExames() {
		return this.exames;
	}

	public void setExames(Set<BDExame> exames) {
		this.exames = exames;
	}
	
	@Override
	public String toString() {
		return nome;
	}

}
