package com.segmed;
// default package
// Generated 16/05/2018 21:50:25 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "CLIENTES", schema = "SEGMED")
public class BDClientes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoCliente;
	private String nome;
	private String bairro;
	private String cidade;
	private String endereco;
	private String uf;
	private String cep;
	private String telefone;
	private String celular;
	private String email;
	private String cnpj;
	private Set<BDClientecolaborador> clientecolaboradors = new HashSet<BDClientecolaborador>(0);
	private Set<BDExame> exames = new HashSet<BDExame>(0);

	public BDClientes() {
	}

	public BDClientes(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	public BDClientes(String nome, String bairro, String cidade, String endereco, String uf,
			String cep, String telefone, String celular, String email, String cnpj) {
		this.nome = nome;
		this.bairro = bairro;
		this.cidade = cidade;
		this.endereco = endereco;
		this.uf = uf;
		this.cep = cep;
		this.telefone = telefone;
		this.celular = celular;
		this.email = email;
		this.cnpj = cnpj;
	}

	@Id
	@GeneratedValue(generator="seq_clientes", strategy=GenerationType.AUTO)
	@SequenceGenerator(name="seq_clientes", sequenceName="seq_clientes", initialValue=1)
	@Column(name = "codigo_cliente", unique = true, nullable = false)
	public int getCodigoCliente() {
		return this.codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	@Column(name = "nome", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "bairro", length = 30)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade", length = 30)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "endereco", length = 30)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "uf", length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "cep", length = 30)
	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	@Column(name = "telefone", length = 30)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "celular", length = 30)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "cnpj", length = 30)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<BDClientecolaborador> getClientecolaboradors() {
		return this.clientecolaboradors;
	}

	public void setClientecolaboradors(Set<BDClientecolaborador> clientecolaboradors) {
		this.clientecolaboradors = clientecolaboradors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<BDExame> getExames() {
		return this.exames;
	}

	public void setExames(Set<BDExame> exames) {
		this.exames = exames;
	}
	
	@Override
	public String toString() {
		return nome;
	}

}
