package com.segmed;
// default package
// Generated 16/05/2018 21:50:25 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Exameitem generated by hbm2java
 */
@Entity
@Table(name = "EXAMEITEM", schema = "SEGMED")
public class BDExameitem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoExameitem;
	private BDExame exame;
	private BDServico servico;
	private BDDescricao descricao;

	public BDExameitem() {
	}

	public BDExameitem(int codigoExameitem) {
		this.codigoExameitem = codigoExameitem;
	}
	
	public BDExameitem(BDExame exame, BDServico servico, BDDescricao descricao) {
		this.exame = exame;
		this.servico = servico;
		this.descricao = descricao;
	}

	public BDExameitem(int codigoExameitem, BDExame exame, BDServico servico, BDDescricao descricao) {
		this.codigoExameitem = codigoExameitem;
		this.exame = exame;
		this.servico = servico;
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(generator="seq_exameitem", strategy=GenerationType.AUTO)
	@SequenceGenerator(name="seq_exameitem", sequenceName="seq_exameitem", initialValue=1)
	@Column(name = "codigo_exameitem", unique = true, nullable = false)
	public int getCodigoExameitem() {
		return this.codigoExameitem;
	}

	public void setCodigoExameitem(int codigoExameitem) {
		this.codigoExameitem = codigoExameitem;
	}

	@ManyToOne
	@JoinColumn(name = "codigo_exame", referencedColumnName = "codigo_exame")
	public BDExame getExame() {
		return this.exame;
	}

	public void setExame(BDExame exame) {
		this.exame = exame;
	}

	@ManyToOne
	@JoinColumn(name = "codigo_servico", referencedColumnName = "codigo_servico")
	public BDServico getServico() {
		return this.servico;
	}

	public void setServico(BDServico servico) {
		this.servico = servico;
	}
	
	@ManyToOne
	@JoinColumn(name = "codigo_descricao", referencedColumnName = "codigo_descricao")
	public BDDescricao getDescricao() {
		return descricao;
	}

	public void setDescricao(BDDescricao descricao) {
		this.descricao = descricao;
	}
	
}
