package com.segmed;
// Generated 25/05/2018 11:52:52 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoginTabela generated by hbm2java
 */
@Entity
@Table(name = "LOGIN_TABELA", schema = "SEGMED")
public class BDLoginTabela implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoLogin;
	private String usuario;
	private String senha;

	public BDLoginTabela() {
	}

	public BDLoginTabela(int codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	public BDLoginTabela(String usuario, String senha) {
		this.usuario = usuario;
		this.senha = senha;
	}

	@Id

	@Column(name = "codigo_login", unique = true, nullable = false)
	public int getCodigoLogin() {
		return this.codigoLogin;
	}

	public void setCodigoLogin(int codigoLogin) {
		this.codigoLogin = codigoLogin;
	}

	@Column(name = "usuario", length = 30)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "senha", length = 30)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}
