package com.segmed;
// default package
// Generated 16/05/2018 21:50:25 by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name = "SERVICO", schema = "SEGMED")
public class BDServico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoServico;
	private String nome;
	private Set<BDExameitem> exameitems = new HashSet<BDExameitem>(0);

	public BDServico() {
	}

	public BDServico(String nome) {
		this.nome = nome;
	}

	public BDServico(int codigoServico, String nome, Set<BDExameitem> exameitems) {
		this.codigoServico = codigoServico;
		this.nome = nome;
		this.exameitems = exameitems;
	}

	@Id
	@GeneratedValue(generator="seq_servico", strategy=GenerationType.AUTO)
	@SequenceGenerator(name="seq_servico", sequenceName="seq_servico", initialValue=1)
	@Column(name = "codigo_servico", unique = true, nullable = false)
	public int getCodigoServico() {
		return this.codigoServico;
	}

	public void setCodigoServico(int codigoServico) {
		this.codigoServico = codigoServico;
	}

	@Column(name = "nome", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servico")
	public Set<BDExameitem> getExameitems() {
		return this.exameitems;
	}

	public void setExameitems(Set<BDExameitem> exameitems) {
		this.exameitems = exameitems;
	}
	
	public String toString() {
		return nome;
	}

}
